parameters:
#    zfr_mailchimp.example.class: ZfrMailChimpBundle\Example

services:
  zfr_mailchimp:
    class: ZfrMailChimpBundle\Services\MailChimpHandler
    arguments: ["%zfr_mail_chimp.api_key%,%zfr_mail_chimp.async%"]
